### ISSUE TITLE
Can't run zoc - An unknown error occurred

### ISSUE THREAD

**Issue by Vinatorul** [ozkriff/zoc#115]
I am using Ubuntu 12.04.
Tried to run with `--verbose` and got such output:
```
GL_VERSION: 2.1.2 NVIDIA 304.125
GL_SHADING_LANGUAGE_VERSION: 1.20 NVIDIA via Cg compiler
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce 310M/PCIe/SSE2
thread '<main>' panicked at '', src/zgl/src/shader.rs:175
Process didn't exit successfully: `target/debug/zoc` (exit code: 101)
```

**Comment by ozkriff** [comment]
Так, оно не может скомпилировать шейдер и вместо лога ошибки выдает пустоту, хм.

Можешь попробовать так?

```diff
diff --git a/src/visualizer/src/visualizer.rs b/src/visualizer/src/visualizer.rs
index 3f44b37..e80bfb4 100644
--- a/src/visualizer/src/visualizer.rs
+++ b/src/visualizer/src/visualizer.rs
@@ -81,7 +81,7 @@ use map_text::{MapTextManager};
 const BG_COLOR: Color3 = Color3{r: 0.8, g: 0.8, b: 0.8};
 
 static VS_SRC: &'static str = "\
-    #version 100\n\
+    #version 120\n\
     uniform mat4 mvp_mat;\n\
     attribute vec3 position;\n\
     attribute vec2 in_texture_coordinates;\n\
@@ -94,8 +94,7 @@ static VS_SRC: &'static str = "\
 ";
 
 static FS_SRC: &'static str = "\
-    #version 100\n\
-    precision mediump float;\n\
+    #version 120\n\
     uniform sampler2D basic_texture;\n\
     uniform vec4 basic_color;
     varying vec2 texture_coordinates;\n\

```

А то "версия 100" это для OpenGL ES, а не десктопоного, мало ли.

**Comment by Vinatorul** [comment]
Сейчас и 100, и 120, и 140 прекрасно работают. 
Однако `GL_VERSION` изменился `GL_VERSION: 2.1.2 NVIDIA 304.128`, был 125.
Подозреваю, что вчера я какой-то апдейт не заметил и часть библиотек драйвера обновилась до 128й версии, а ядро осталось 125й.
Спасибо за советы.

На правах оффтопа: если забыть или потерять какой-либо ассет, то при запуске всё падает c
```
thread '<main>' panicked at 'Can`t open file', ../src/libcore/option.rs:330
```
при этом не ясно, какой файл отстутсвует.

И ещё 
> latest rust-nightly is required

На `stable` всё отлично работает.

**Comment by ozkriff** [comment]
Ну здорово, что заработало. Я подумываю заменить свои велосипедные обвязки вокруг OpenGL на glium - там-то сложностей с инициализацией на разных платформах должно быть меньше.

Про ресурсы - это знаю. Когда Result::expect стабилизируется, тогда нормальное сообщение об ошибке будет. Вроде, скоро уже.

Про версию - да, это я давненько писал еще, тогда стабильной пользоваться вообще невозможно было. Но и сейчас под андроид все равно без ночной версии не соберешь - android-rs-glue требует для сборки.

В общем, спасибо, что интересуешься) Эх, хотя zoc`у до играбельного состояния еще очень и очень далеко, конечно.

**Comment by Vinatorul** [comment]
`glium` вещь хорошая, но там шейдеры точно так же `raw` строками задаются. Хотя `glium` как-то пережил проблему и работал вчера.

Для использования `zoc` как примера, я думаю, сейчас самое удачное время, т.к. игра ещё не успела разрастись, а основные модули и свзяки уже написаны. Спасибо за проделанную работу, пойду изучать :)

**Comment by ozkriff** [comment]
Сам текст шейдеров-то да, но вот процесс инициализации там намного более умный. Если ты чего-то сам писать собираешься, то я советую сразу брать glium, а не мучать gl-rs)

zoc как пример, может и ничего. Только учитывай, что я его черепашьим темпом и забрасывая на месяц-другой потихоньку ковыряю аж [с декабря 2013 года](https://github.com/ozkriff/marauder/blob/52f2a76/main.rs). Устаревшего кода и неидиоматичного для современной ржавчины тут есть, несмотря на скромный объем исходников.

Если вдруг будут какие вопросы - можешь в https://gitter.im/ozkriff писать, так быстрей выйдет.
