### ISSUE TITLE
Add assets repo as submodule

### ISSUE THREAD

**Issue by Vinatorul** [ozkriff/zoc#140]
Is it possible to add assets repo as submodule to this repo? It will be more easier to fetch `zoc`. Also, I think, you will be able to fetch it via `cargo`.

**Comment by ozkriff** [comment]
I don't like git submodules and not sure about correctness of using cargo's build.rs for this.

Не нравится мне идея использовать подмодули для такого. Я их вообще не люблю. Сargo, как по мне, тоже таким заниматься не должен - его задача собирать бинарь. Но спасибо за комментарий, я еще подумаю на эту тему :) .
