### ISSUE TITLE
Update devlog + mention it in readme

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zoc#177]
Блин, опять я журнал забросил. Надо все черновики своих записей в ozkriff.github.io выложить, да ссылку в ридми прописать.

**Comment by ozkriff** [comment]
Я не забыл, я в фоне потихоньку ковыряю, чесслово! Никак не могу добить запись про слоты.

**Comment by ozkriff** [comment]
Соберись, тряпка! Сколько можно тянуть?!

![злой начальник](http://www.cppr.info/images/2014/1/esli-u-vas-grubyj-nachalnik_2.jpg)

**Comment by ozkriff** [comment]
Нет, Тряпка так и не собрался. Боюсь, я забиваю на ведение https://ozkriff.github.io и буду только писать TWIZ`ы да стараться более подробно отписываться тут в задачах обо всем.

**Comment by reverendhomer** [comment]
"won't fix" is not solution.
