### ISSUE TITLE
android: Depth buffer problems on Letv Le 1s

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zoc#248]
Letv Le 1s, Andoid 6.0, Opengl ES 3.1, MTK6795

https://gist.github.com/ozkriff/6d7eae2d40251054d960a3e224935485

**Comment by ozkriff** [comment]
This is how it looks on this phone after the firmware update:

![](http://i.imgur.com/8F0BLBN.jpg)

wow.. z-fighting? bad vertex indices? something else?

**Comment by ozkriff** [comment]
I'll try to update main deps and build a new apk in a few days. Maybe it'll go away on its own? :)

**Comment by ozkriff** [comment]
See https://github.com/gfx-rs/gfx/issues/1188

**Comment by shmutalov** [comment]
Changing a precision solves problem:
https://github.com/gfx-rs/gfx/issues/1188#issuecomment-279963808

**Comment by ozkriff** [comment]
Ok, so we need to set `highp` in fragment shader only.

**Comment by ozkriff** [comment]
Done in https://github.com/ozkriff/zoc/tree/WIP_248_glsl_es_precision

@shmutalov Can you check if it still works on your phone?

**Comment by shmutalov** [comment]
@ozkriff works as expected. No problems with Z-buffer )
