### ISSUE TITLE
Consistent labels for clickable widgets

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zoc#265]
Put square brackets around all clickable text

- `start hotseat` -> `[start hotseat]`
- `move` -> `[move]`
- `attack <jeep> 56%` -> `[attack <jeep>: 56%]`
- etc

**Comment by Vinatorul** [comment]
I think semigraphics tables should feat better:
```
┌───────────────┐
│ start hotseat │
└───────────────┘
┌──────┐
│ move │
└──────┘
┌────────────────────┐
│ attack <jeep>: 56% │
└────────────────────┘
```
