### ISSUE TITLE
Did u  mind if same one help u with game?

### ISSUE THREAD

**Issue by Codenator81** [ozkriff/zoc#75]
Заинтересован помочь с игрой так как хочу освоить Rust ))

**Comment by ozkriff** [comment]
Привет. Спасибо, но на данном этапе я бы предпочел один тихонько ковырять код :) .

Посмотри, например, www.piston.rs - они, насколько я знаю, всегда рады новой крови)

**Comment by Codenator81** [comment]
Ок я уже нашёл себе жертву )))
